# Generated by Django 4.1.6 on 2023-02-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("noteapp", "0003_tag_user_alter_note_user_tag_tag of username"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tag",
            name="tag of username",
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=25),
        ),
    ]
