# Generated by Django 4.1.6 on 2023-02-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_remove_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.FloatField(default=0.0),
        ),
    ]
