# Generated by Django 4.1.6 on 2023-02-12 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_downloads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloads',
            name='size',
        ),
    ]
